#!/usr/bin/env bash
# A bash script that installs nginx

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
echo "server {
    listen 80;
    server_name _;
    location / {
        root /var/www/html;
        index index.html index.htm;
        add_header Content-Type 'text/plain';
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default
sudo service nginx reload
