#!/usr/bin/env bash
# the script configures the Nginx server to have a custom 404 page that contains the
# string Ceci n'est pas une page

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

echo "server {
    listen 80;
    server_name _;

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }

}" | sudo tee /etc/nginx/sites-available/custom_404
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default
sudo service nginx restart
