#!/usr/bin/env bash
# The script pings an IP adress passed as an argument
ip_address="$1"
if [ $# -eq 0 ]; then
 echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
 ping "$ip_address" -c5
fi
