#!/usr/bin/env bash
# This script configures a server to listen on port 8
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
