#!/usr/bin/env bash
#This script stops "4-to_infinity_and_beyond" process.
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -z "$pid" ]; then
 echo "4-to_infinity_and_beyond process is not running."
else
 kill "$pid"
 echo "4-to_infinity_and_beyond process has been stopped."
fi
