#!/usr/bin/env bash
This script stops "4-to_infinity_and_beyond" process.
pid=$(pgrep -f "4-to_infinity_and_beyond")
# Check if the process is running
if [ -n "$pid" ]; then
    echo "Stopping process with PID $pid..."
    # Send a SIGTERM signal to gracefully terminate the process
    kill "$pid"
else
    echo "Process '4-to_infinity_and_beyond' is not running."
fi
