#!/usr/bin/env bash
#This script stops "4-to_infinity_and_beyond" process.
./4-to_infinity_and_beyond &

PID=$!

echo "Process 4-to_infinity_and_beyond started with PID: $PID"

read -p "Press any key to stop the process..."

kill $PID
