#!/usr/bin/env bash
# This script is displaying time for 12 hours and 59 minutes
hour=0
minute=1

while [ $hour -le 12 ]
do
  if [ $hour -eq 0 ]
  then
    echo "Hour: 0"
  else
    echo "Hour: $hour"
  fi

  while [ $minute -le 59 ]
  do
    echo $minute
    ((minute++))
  done

  ((hour++))
  minute=0
done | head -n 70
