#!/usr/bin/env bash
# This script is displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
for file in *; do
  # Check if the file is not hidden and is a regular file
  if [[ ! "$file" =~ ^\. && -f "$file" ]]; then
    # Use cut
    name_part=$(echo "$file" | cut -d'-' -f2-)
    echo "$name_part"
  fi
done
