#!/usr/bin/env bash
# The script configures the container to run as nginx listening on all active IPs on port # 8080
pkill apache2
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.config
sudo -u nginx service nginx restart
