#!/usr/bin/env bash
# The script configures the containerfor nginx  to run as the nginx user
pkill apache2
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.config
sudo -u nginx service nginx restart
