#!/usr/bin/env bash
# script configuring nginx to serve from /airbnb-onepage/

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name 18.209.179.13

    add_header X-Served-By 307440-web-01;

    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }

    location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}
